### CHANGE BEFORE DEPLOY ####
#baseurl = "http://10.0.0.10/"
baseurl = "https://www.michaelgoll.com/"
languageCode = "en-us"
title = "Michael Goll"
theme = "hugo-strata-theme"
disqusShortname = "gollmj"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-36067780-1"
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Michael Goll"
	description = "Solving difficult problems"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "Me2.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Data Integration"
		bio2 = "Software Consultant "
		# The icons will be shown if you enter your username
		twitter = ""
		github = "gollmj"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "https://www.linkedin.com/in/michael-goll-074656a2"

		copyright = [
			"&copy; Michael Goll",
			"Design: [Michael Goll](//michaelgoll.com)",
			"Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Utilize the data you already have to streamline your business"
		content = "<br>[Send me an email](https://www.michaelgoll.com/#contact-form) to find out how I can help solve your business problems."


	[params.portfolio]
		hide  = false
		title = "Most Recent Tools"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "../post/index.html"
			thumb = "thumbs/jitterbit.jpg"
			title = "Jittbit Integration."
			description = "Salesforce Integration"

		[[params.portfolio.gallery]]
			image = "../post/index.html"
			thumb = "thumbs/rhapsody.jpg"
			title = "Orion Rhapsody"
			description = "JSON - HL7 - REST"

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/IIB.jpg"
			title = "IBM Integration Bus"
			description = "Message Broker v9 Certified"

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/appConnect.jpg"
			title = "IBM App Connect (CastIron)"
			description = "Websphere Cast Iron"

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Feel free to send me an email about your business issues or just to say hello!"

		address = [
			"Currently:",
			"Athens, Greece",
		]
		phone = "+1-610-462-4393"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "michael@michaelgoll.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
